name: sanitizers

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        sanitizer:
          - asan
          - lsan
          - tsan
          - ubsan
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          max-size: 2G
          key: ${{ github.job }}-${ matrix.sanitizer }
      - name: Build tests
        env:
          CB_NUMBER_OF_JOBS: 2
          CB_COMPILER: clang-15
          CB_SANITIZER: ${{ matrix.sanitizer }}
        run: ./bin/build-tests
      - name: Archive artifacts
        working-directory: cmake-build-tests-${{ matrix.sanitizer }}/test
        run:
          mkdir -p tests-${{ matrix.sanitizer }};
          find . -perm /u+x -type f -name 'test_*' -exec mv -v -t tests-${{ matrix.sanitizer }} {} +
      - uses: actions/upload-artifact@v4
        with:
          retention-days: 1
          name: tests-${{ matrix.sanitizer }}
          path: cmake-build-tests-${{ matrix.sanitizer }}/test/tests-${{ matrix.sanitizer }}/*

  # test:
  #   strategy:
  #     fail-fast: false
  #     matrix:
  #       sanitizer:
  #         - asan
  #         - lsan
  #         - tsan
  #         - ubsan
  #       tls:
  #         - tls
  #         - plain
  #   steps:
  #     - name: Install dependencies
  #       run: |
  #         sudo apt-get update -y
  #         sudo apt-get install -y libssl-dev cmake curl wget gnupg2 gdb
  #         wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
  #         sudo bash -c "echo 'deb https://apt.llvm.org/focal/ llvm-toolchain-focal-13 main' >> /etc/apt/sources.list"
  #         sudo apt-get update -y
  #         sudo apt-get install -y clang-13 clang-tools-13
  #     - name: Run tests
  #       timeout-minutes: 30
  #       env:
  #         CB_SANITIZER: ${{ matrix.sanitizer }}
  #         TEST_SERVER_VERSION: 7.2.3
  #         TEST_CONNECTION_STRING: ${{ matrix.tls == 'tls' && 'couchbases://127.0.0.1?trust_certificate=cluster.crt' || 'couchbase://127.0.0.1' }}
  #         TEST_LOG_LEVEL: trace
  #       run: ./bin/run-unit-tests
  #
